// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AplicacionWebProgramacion3.Models;

public partial class plantasDBContext : DbContext
{
    public plantasDBContext(DbContextOptions<plantasDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Fertilizantes> Fertilizantes { get; set; }

    public virtual DbSet<Plantas> Plantas { get; set; }

    public virtual DbSet<Suelos> Suelos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Fertilizantes>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Fertiliz__3213E83F2C30A0AA");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Nombre)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.Composicion)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("composicion");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasColumnName("descripcion");
            entity.Property(e => e.Forma)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("forma");
            entity.Property(e => e.Tipo)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("tipo");
        });

        modelBuilder.Entity<Plantas>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Plantas__3213E83FB3CA9534");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.AlturaMaxima).HasColumnName("altura_maxima");
            entity.Property(e => e.Autor)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("autor");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasColumnName("descripcion");
            entity.Property(e => e.EpocaFloracion)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("epoca_floracion");
            entity.Property(e => e.NombreCientifico)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("nombre_cientifico");
            entity.Property(e => e.NombreVulgar)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nombre_vulgar");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}